import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const VazirFont = localFont({
  src: "./fonts/vazir.woff2"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "G5 Generator | Fakharnia.com",
  description: "Generated by Fakharnia.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <div id='testdiv' style={{ height: "1in", left: "-100%", position: "absolute", top: "-100%", width: "1in" }}></div>
      </body>
    </html>
  );
}
